# Generated by Django 4.2.5 on 2023-12-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="no_of_likes",
            field=models.IntegerField(default=0),
        ),
    ]
