# Generated by Django 4.2.5 on 2023-12-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userauth", "0003_post_no_of_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(upload_to="post_images"),
        ),
    ]
